name: Call API with Secret

on: push

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call external API using secret
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://api.example.com/data
